name: space-plan to DO Registery

on:
  push:
    branches: [workflow]
    paths:
      - "challenges/OSINT/space-plan/source/**"
      - ".github/workflows/space-plan.yml"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build image 
        run: docker build -t space-plan challenges/OSINT/space-plan/source

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag image 
        run: docker tag space-plan ${{ secrets.REGISTRY_NAME }}/space-plan:latest

      - name: Push image to DO Container Registry 
        run: docker push ${{ secrets.REGISTRY_NAME }}/space-plan:latest
