name: this-outta-be-large-enough-right to DO Registery

on:
  push:
    branches: [workflow]
    paths:
      - "challenges/binary-exploitation/this-outta-be-large-enough-right/source/**"
      - ".github/workflows/this-outta-be-large-enough-right.yml"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Build image 
        run: docker build -t this-outta-be-large-enough-right challenges/binary-exploitation/this-outta-be-large-enough-right/source

      - name: Tag image 
        run: docker tag this-outta-be-large-enough-right ${{ secrets.REGISTRY_NAME }}/this-outta-be-large-enough-right:latest

      - name: Push image to DO Container Registry 
        run: docker push ${{ secrets.REGISTRY_NAME }}/this-outta-be-large-enough-right:latest
